#!/bin/bash

## Quickselect
#for rep in {1..996}; do for j in {0..19999}; do ./quickselect 20000 $j; done; done
# for rep in {0..19999}; do ./statistics out/quickselect/quickselect$rep.txt 996 4 $rep; done;

## Floyd Rivest
#for rep in {1..996}; do for n in {1..20000}; do ./floydrivest $n; done; done
#for rep in {1..20000}; do ./statistics out/floydrivest/floydrivest$rep.txt 996 2 $rep; done

## Median of t
#for rep in {1..996}; do for j in {0..19999}; do ./quickselect-median-of-t 20000 $j 1; done; done
