#!/bin/bash

#for rep in {1..490}; do for j in {0..19999}; do ./quickselect 20000 $j; done; done

# for rep in {0..19999}; do ./statistics out/quickselect/quickselect$rep.txt 4427 4 $rep; done;

#for rep in {1..490}; do for n in {1..20000}; do ./floydrivest $n; done; done
for rep in {1..20000}; do ./statistics out/floydrivest/floydrivest$rep.txt 490 2 $rep; done

#for rep in {1..490}; do for j in {0..19999}; do ./quickselect-median-of-3 20000 $j; done; done
